### PR TITLE
Fix switch account

### LINKED ISSUE #772: [bug]Cannot read property 'getUserName' of undefined
### Provide Your Network Information

Local operating environment
operating system: Win10 x64
Chrome version: chrome 60.0.3112.113 x32
Wechaty version: 

> tested is bad: `0.8.179 - 0.8.191` 
>tested is ok: `0.8.174` - `0.8.178`

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
`cd example && ts-node ding-dong-bot.ts`

```
> wechaty@0.8.179 doctor E:\CodeWork\fork\wechaty
> npm run check-node-version && ts-node bin/doctor


> wechaty@0.8.179 check-node-version E:\CodeWork\fork\wechaty
> check-node-version --node ">= 6.9"

node: 8.1.4
npm: 5.0.3
yarn: 0.27.5
17:08:52 SILL Brolog WECHATY_LOG set level to silly
17:08:52 INFO Config registering process.on("unhandledRejection") for development/debug
17:08:53 SILL StateSwitch constructor(Wechaty, standby)
17:08:53 VERB Wechaty contructor()
17:08:53 VERB Doctor constructor()
17:08:53 VERB Doctor testTcp()
17:08:53 SILL Doctor testTcp() client connected

  #### Wechaty Doctor

  1. Wechaty version: #git[7c107d9]
  2. Windows_NT x64 version 10.0.15063 memory 8071/16324 MB
  3. Docker: false
  4. Node version: v8.1.4
  5. Tcp IPC TEST: PASS
  6. Chromedriver: Error: spawnSync chromedriver ENOENT

17:08:53 SILL Doctor testTcp() server closed
```

### Expected behavior

After logging out once, exit the program and start again, by reading the demo.wechaty.json file to get the cookie, log in smoothly, and use all the features normally.

### Actual behavior

After the start again, the problem is as follows:

```
16:57:44 SILL PuppetWebBrowser Browser.execute(" const callback = arguments[arguments.length - 1] const isAsync = (typeof  ... ")
16:57:44 SILL StateSwitch Browser:target() is open
16:57:44 SILL StateSwitch Browser:current() is open
16:57:44 VERB PuppetWebEvent onServerLog(login(page refresh))
16:57:44 VERB PuppetWebEvent onServerLogin(page refresh, 0)
16:57:44 ERR PuppetWebEvent onServerLogin() exception: TypeError: Cannot read property 'getUserName' of undefined
TypeError: Cannot read property 'getUserName' of undefined
    at PuppetWeb.<anonymous> (E:\CodeWork\fork\wechaty\src\puppet-web\event.ts:252:36)
    at Generator.next (<anonymous>)
    at E:\CodeWork\fork\wechaty\src\puppet-web\event.ts:7:71
    at Promise (<anonymous>)
    at __awaiter (E:\CodeWork\fork\wechaty\src\puppet-web\event.ts:3:12)
    at PuppetWeb.onServerLogin (E:\CodeWork\fork\wechaty\src\puppet-web\event.ts:203:12)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at WebSocket.client.on.data (E:\CodeWork\fork\wechaty\src\puppet-web\server.ts:150:12)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (E:\CodeWork\fork\wechaty\node_modules\ws\lib\WebSocket.js:143:47)
    at Receiver.dataMessage (E:\CodeWork\fork\wechaty\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (E:\CodeWork\fork\wechaty\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (E:\CodeWork\fork\wechaty\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (E:\CodeWork\fork\wechaty\node_modules\ws\lib\Receiver.js:139:10)
    at TLSSocket._ultron.on (E:\CodeWork\fork\wechaty\node_modules\ws\lib\WebSocket.js:139:22)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at TLSSocket.Readable.push (_stream_readable.js:197:10)
    at TLSWrap.onread (net.js:589:20)
16:57:44 ERR Config ###########################
16:57:44 ERR Config unhandledRejection: TypeError: Cannot read property 'getUserName' of undefined [object Promise]
16:57:44 ERR Config ###########################
16:57:44 ERR Config unhandledRejection::catch(Cannot read property 'getUserName' of undefined)
Config TypeError: Cannot read property 'getUserName' of undefined
    at PuppetWeb.<anonymous> (E:\CodeWork\fork\wechaty\src\puppet-web\event.ts:252:36)
    at Generator.next (<anonymous>)
    at E:\CodeWork\fork\wechaty\src\puppet-web\event.ts:7:71
    at Promise (<anonymous>)
    at __awaiter (E:\CodeWork\fork\wechaty\src\puppet-web\event.ts:3:12)
    at PuppetWeb.onServerLogin (E:\CodeWork\fork\wechaty\src\puppet-web\event.ts:203:12)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at WebSocket.client.on.data (E:\CodeWork\fork\wechaty\src\puppet-web\server.ts:150:12)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (E:\CodeWork\fork\wechaty\node_modules\ws\lib\WebSocket.js:143:47)
    at Receiver.dataMessage (E:\CodeWork\fork\wechaty\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (E:\CodeWork\fork\wechaty\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (E:\CodeWork\fork\wechaty\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (E:\CodeWork\fork\wechaty\node_modules\ws\lib\Receiver.js:139:10)
    at TLSSocket._ultron.on (E:\CodeWork\fork\wechaty\node_modules\ws\lib\WebSocket.js:139:22)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at TLSSocket.Readable.push (_stream_readable.js:197:10)
    at TLSWrap.onread (net.js:589:20)
(node:16896) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)


16:57:48 SILL Contact contactGetter(@730ea843713a538f1a4d8df74555fc000c8b4d981c8e26cd8fc93a1c64ac284e) resolved
16:57:48 SILL Message ready()
16:57:48 SILL Contact ready()
16:57:48 SILL Contact ready()
<杉木>:{TEXT}ding
16:57:48 ERR Bot on(message) exception: Error: no user or no from
```

### Steps to reproduce the behavior (and fixes, if any)

1. Once you log in, close and log in again. (auto login)
2. Send the message `ding` to the bot, output `ERR Bot on(message) exception: Error: no user or no from` and can't send any msg from the bot.

### test
0.8.178 and lower versions is no such problem.
0.8.179 - 0.8.191 This problem must occur
Suspect that the problem may be caused by https://github.com/Chatie/wechaty/commit/3f7791ef4fddfc4c32761d35223ad08bf4c76891

### PR DESCRIPTION
**Pull request by binsee**
1. Support for find elements on pages of different languages
2. fix uncaughtException in onServerLogin()

uncaughtException log:
```
17:33:29 VERB StateSwitch Wechaty:current(ready,true) <- (ready,false)
ReferenceError: arguments is not defined
    at Timeout.setTimeout (E:\CodeWork\fork\wechaty\src\puppet-web\event.ts:249:35)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
17:33:30 ERR Bot uncaughtException: ReferenceError: arguments is not defined
Wechaty exit 99 because of uncaughtException
```

fix #772

### CODE REVIEW

File: src/puppet-web/event.ts [hunk 1]
```diff
@@ -244,6 +244,10 @@ async function onServerLogin(this: PuppetWeb, data, attempt = 0): Promise<void>
   // if `login` event fired before this.bridge inited, we delay the event for 1 second.
   if (!this.bridge) {
     log.verbose('PuppetWebEvent', 'onServerLogin() fired before bridge inited. delay for 1 second.')
+    if (!arguments) {
+      log.warn('PuppetWebEvent', 'onServerLogin() arguments is null')
+      throw new Error('onServerLogin() arguments is null')
```
Comment (binsee) [inline src/puppet-web/event.ts]: When I use the cookie file to run again, I do not understand why it is still running after it is thrown

**Comment by zixia** [comment]
It seems we should use `arguments` inside the arrow function carefully.

See: https://stackoverflow.com/questions/33298315/why-arguments-is-not-defined-in-arrow-function-in-es6

File: src/puppet-web/event.ts [hunk 2]
```diff
@@ -244,6 +244,10 @@ async function onServerLogin(this: PuppetWeb, data, attempt = 0): Promise<void>
   // if `login` event fired before this.bridge inited, we delay the event for 1 second.
```
Comment (zixia) [inline src/puppet-web/event.ts]: `const args = Array.prototype.slice.call(arguments)`

File: src/puppet-web/event.ts [hunk 3]
```diff
@@ -244,6 +244,10 @@ async function onServerLogin(this: PuppetWeb, data, attempt = 0): Promise<void>
...
   if (!this.bridge) {
     log.verbose('PuppetWebEvent', 'onServerLogin() fired before bridge inited. delay for 1 second.')
+    if (!arguments) {
+      log.warn('PuppetWebEvent', 'onServerLogin() arguments is null')
+      throw new Error('onServerLogin() arguments is null')
+    }
     setTimeout(() => {
       onServerLogin.apply(this, arguments)
```
Comment (zixia) [inline src/puppet-web/event.ts]: `onServerLogin.apply(this, args)`

We can not use `arguments` directly because it's not a **real** array.

See: https://stackoverflow.com/a/676728/1123955

File: src/puppet-web/event.ts (hunk 1 above)
Comment (zixia) [reply src/puppet-web/event.ts]: Please use `args` to replace the `arguments` in the code, then I believe we need not check `!arguments` again because we can get an empty array for `args`.

File: src/puppet-web/event.ts (hunk 2 above)
Comment (binsee) [reply src/puppet-web/event.ts]: OK, has used args to replace argments.

**Comment by lijiarui** [comment]
Thanks!  I tried this code, but always get the following result:
```shell
12:29:54 VERB PuppetWeb initBridge() done
12:29:54 VERB PuppetWebBrowser clickSwitchAccount()
12:29:54 SILL PuppetWebBrowser clickSwitchAccount() button not found: no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@class,'association') and contains(@class,'show')]/a[@ng-click='qrcodeLogin()']"}
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
12:29:54 VERB StateSwitch Puppet:current(live,true) <- (live,false)
```

Cannot get auto click silly log.

**Comment by binsee** [comment]
@lijiarui 
I tried this code to work properly.
When using the cookie file to start again, if the interval is very short, do not need to re-scan landing.
If you modify the key value in the cookie file to make it invalid, you will find that when you start again, the switch account button will be automatically clicked.
Because the normal landing did not switch account button, it will lead to abnormal, but it was captured, will not affect the operation.

**Comment by zixia** [comment]
In order to make the log clearer, I suggest we change the log code like this:
```diff
- log.silly('PuppetWebBrowser', 'clickSwitchAccount() button not found: %s', e && e.message || e) 
+ log.silly('PuppetWebBrowser', 'clickSwitchAccount() no button found')
```

This change might be able to make the log less confusing.

**Comment by zixia** [comment]
@lijiarui could you please review this pr and approve it if it lgty?

**Comment by zixia** [comment]
Thanks all for pr/review the code!
