### PR TITLE
fix(wechaty-bro): resolved emit RECALLED type msg (fix #8)

### LINKED ISSUE #8: it seems RECALLED: 10002 message dose't trigger on('message') event
i tested the ding-dong-bot and recalled some message , it dose not trigger the event.

### PR DESCRIPTION
**Pull request by binsee**
fix #8

image

### CODE REVIEW

**Comment by binsee** [comment]
There is a small problem with this way, after the recall message, the web page displays a blank message.
But does not affect the use.

File: src/puppet-web/wechaty-bro.js [hunk 1]
```diff
@@ -378,6 +379,19 @@
     })
     return true
   }
+
+  function hookProcess() {
+    var chatFactory = WechatyBro.glue.chatFactory
+    var rootScope = WechatyBro.glue.rootScope
```
Comment (zixia) [inline src/puppet-web/wechaty-bro.js]: `rootScope` is not needed at here.

File: src/puppet-web/wechaty-bro.js [hunk 2]
```diff
@@ -378,6 +379,19 @@
...
+    // hook chatFactory._recalledMsgProcess, resolve emit RECALLED type msg
+    chatFactory.__recalledMsgProcess = chatFactory._recalledMsgProcess
+    chatFactory._recalledMsgProcess = function (msg) {
+      var _this = this
```
Comment (zixia) [inline src/puppet-web/wechaty-bro.js]: What's the reason that you save `this` to `_this`? 

IMHO, It seems not necessary to do that inside this function?

File: src/puppet-web/wechaty-bro.js [hunk 3]
```diff
@@ -378,6 +379,19 @@
...
+      _this.__recalledMsgProcess(msg)
```
Comment (zixia) [inline src/puppet-web/wechaty-bro.js]: How about use `chatFactory` at here instead of `this`?

Like: `chatFactory.__recalledMsgProcess` and `__recalledMsgProcess.addChatMessage`

File: src/message.ts [hunk 4]
```diff
@@ -604,6 +604,34 @@ export class Message implements Sayable {
...
+   * @example
+   * ```javascript
+   * Bot.on('message', async m => {
+   *   if (m.type() === MsgType.RECALLED) {
+   *     await m.say(`You recalled a message, message ID：${m.getRevokeId()}`)
+   *   }
+   * })
+   * ```
+   */
+  public getRevokeId(): string {
```
Comment (zixia) [inline src/message.ts]: Why we need to add this new method?

I did not think it's necessary. 

Please correct me if I'm wrong.

File: src/puppet-web/wechaty-bro.js [hunk 5]
```diff
@@ -76,6 +76,7 @@
     glueToAngular()
     connectSocket()
     hookEvents()
+    hookProcess()
```
Comment (binsee) [inline src/puppet-web/wechaty-bro.js]: I use `hookProcess` because I think in the future may add other hooks. But for now, the term is not clear, I will modify it.

File: src/puppet-web/wechaty-bro.js (hunk 1 above)
Comment (binsee) [inline src/puppet-web/wechaty-bro.js]: i will remove it.

File: src/message.ts (hunk 4 above)
Comment (binsee) [inline src/message.ts]: RECALLED msg, content:
```json
&lt;sysmsg type="revokemsg"&gt;&lt;revokemsg&gt;&lt;session&gt;binsee&lt;/session&gt;&lt;oldmsgid&gt;1056815127&lt;/oldmsgid&gt;&lt;msgid&gt;6991717488370193149&lt;/msgid&gt;&lt;replacemsg&gt;&lt;![CDATA["杉木" 撤回了一条消息]]&gt;&lt;/replacemsg&gt;&lt;/revokemsg&gt;&lt;/sysmsg&gt;
```

use `UtilLib.unescapeHtml(this.obj.content)`
```xml
// the content has been formatted
<sysmsg type="revokemsg">
    <revokemsg>
        <session>binsee</session>
        <oldmsgid>1056815127</oldmsgid>
        <msgid>6991717488370193149</msgid>
        <replacemsg>
            <![CDATA["杉木" 撤回了一条消息]]>
        </replacemsg>
    </revokemsg>
</sysmsg>
```

We need to use getRevokeId () package to extract the code `msgId`

```javascript
const ret = UtilLib.unescapeHtml(this.obj.content).match(/<msgid>(\w+)<\/msgid>/)
```

File: src/puppet-web/wechaty-bro.js (hunk 3 above)
Comment (binsee) [inline src/puppet-web/wechaty-bro.js]: I modified it, it can work:
```javascript
    chatFactory._recalledMsgProcess = function (msg) {
      chatFactory.__recalledMsgProcess(msg)
      chatFactory.addChatMessage(msg)
    }
```

**Comment by binsee** [comment]
RECALLED msg, content:
```json
&lt;sysmsg type="revokemsg"&gt;&lt;revokemsg&gt;&lt;session&gt;binsee&lt;/session&gt;&lt;oldmsgid&gt;1056815127&lt;/oldmsgid&gt;&lt;msgid&gt;6991717488370193149&lt;/msgid&gt;&lt;replacemsg&gt;&lt;![CDATA["杉木" 撤回了一条消息]]&gt;&lt;/replacemsg&gt;&lt;/revokemsg&gt;&lt;/sysmsg&gt;
```

use `UtilLib.unescapeHtml(this.obj.content)`
```xml
// the content has been formatted
<sysmsg type="revokemsg">
    <revokemsg>
        <session>binsee</session>
        <oldmsgid>1056815127</oldmsgid>
        <msgid>6991717488370193149</msgid>
        <replacemsg>
            <![CDATA["杉木" 撤回了一条消息]]>
        </replacemsg>
    </revokemsg>
</sysmsg>
```

We need to use getRevokeId () package to extract the code `msgId`

```javascript
const ret = UtilLib.unescapeHtml(this.obj.content).match(/<msgid>(\w+)<\/msgid>/)
```

File: src/message.ts (hunk 4 above)
Comment (zixia) [inline src/message.ts]: I see.

As my understanding now, the parameter of `_recalledMsgProcess()` is `<sysmsg type="revokemsg">...</sysmsg>`, right?

If so, I think the better procedure might be(in wechaty-bro.js):

1. find the original message for that `msgid`, then 
1. set the message with MsgType.RECALLED, then 
1. use `WechatBro.emit()` to emit that message again. (see: https://github.com/Chatie/wechaty/blob/master/src/puppet-web/wechaty-bro.js#L366)

The above procedure could let the end-user receive a `message` event, with the original message, but with MsgType.RECALLED set. (and no new method need to be introduced)

How about this idea, what do you think?

**Comment by zixia** [comment]
I see.

As my understanding now, the parameter of `_recalledMsgProcess()` is `<sysmsg type="revokemsg">...</sysmsg>`, right?

If so, I think the better procedure might be(in wechaty-bro.js):

1. find the original message for that `msgid`, then 
1. set the message with MsgType.RECALLED, then 
1. use `WechatBro.emit()` to emit that message again. (see: https://github.com/Chatie/wechaty/blob/master/src/puppet-web/wechaty-bro.js#L366)

The above procedure could let the end-user receive a `message` event, with the original message, but with MsgType.RECALLED set. (and no new method need to be introduced)

How about this idea, what do you think?

**Comment by binsee** [comment]
msg.content='&lt;sysmsg type="revokemsg"&gt;&lt;revokemsg&gt;&lt;session&gt;binsee&lt;/session&gt;&lt;oldmsgid&gt;1056815127&lt;/oldmsgid&gt;&lt;msgid&gt;6991717488370193149&lt;/msgid&gt;&lt;replacemsg&gt;&lt;![CDATA["杉木" 撤回了一条消息]]&gt;&lt;/replacemsg&gt;&lt;/revokemsg&gt;&lt;/sysmsg&gt;'

must use `UtilLib.unescapeHtml(this.obj.content)`, return xml text, and use match to get msgId.

**Comment by zixia** [comment]
Could you do those works in the browser, like my last suggestion?

**Comment by binsee** [comment]
Sorry, I read your reply repeatedly and found that I did not fully understand what you meant. I will think again and then update it

**Comment by binsee** [comment]
In the `wechaty-bro` to achieve the` RECALLED` message handling, it looks good results.
But encountered a question that needs to be discussed:

The order in which the code is called will produce a different return effect. Which do we choose?

**Description:** dev_tag is my added field for debugging notes

### Option 1

First `chatFactory._recalledMsgProcess` again `WechatyBro.emit`

Recalled the WebWxApp received the message, rawObj data:

`msg.type()` return `MsgType.RECALLED`
`msg.content()` return `杉木撤回了一条消息`

`msg.rawObj.MMRecall == true`

```json
{"MsgId":"3066610148686027451","FromUserName":"@d4d830178e30550380be2175c454951f","ToUserName":"@ae39ddd7f22214f8f330b68aaa8ec0190702c0c33467b2a23338a77221e6f431",
"MsgType":10002,
"Content":"接收到的消息内容","Status":3,"ImgStatus":1,"CreateTime":1503162116,"VoiceLength":0,"PlayLength":0,"FileName":"","FileSize":"","MediaId":"","Url":"","AppMsgType":0,"StatusNotifyCode":0,"StatusNotifyUserName":"","RecommendInfo":{"UserName":"","NickName":"","QQNum":0,"Province":"","City":"","Content":"","Signature":"","Alias":"","Scene":0,"VerifyFlag":0,"AttrStatus":0,"Sex":0,"Ticket":"","OpCode":0},"ForwardFlag":0,"AppInfo":{"AppID":"","Type":0},"HasProductId":0,"Ticket":"","ImgHeight":0,"ImgWidth":0,"SubMsgType":0,"NewMsgId":3066610148686027300,"OriContent":"","MMPeerUserName":"@d4d830178e30550380be2175c454951f",
"MMDigest":"杉木撤回了一条消息","MMIsSend":false,"MMIsChatRoom":false,"MMUnread":true,"LocalID":"3066610148686027451",
"ClientMsgId":"3066610148686027451",
"MMActualContent":"杉木撤回了一条消息",
"MMActualSender":"@d4d830178e30550380be2175c454951f","MMDigestTime":"1:01","MMDisplayTime":1503162116,"MMTime":"1:01","_h":0,
"MMRecall":true,
"dev_tag":"这是基于原先的消息体"}
```

Recalled the WebWxApp did not received the message, rawObj data:

`msg.type()` return `MsgType.RECALLED`
`msg.content()` return `"杉木" 撤回了一条消息`

```json
{"MsgId":"443731713080375307","FromUserName":"@d4d830178e30550380be2175c454951f","ToUserName":"@ae39ddd7f22214f8f330b68aaa8ec0190702c0c33467b2a23338a77221e6f431",
"MsgType":10002,
"Content":"\"杉木\" 撤回了一条消息","Status":4,"ImgStatus":1,"CreateTime":1503162122,"VoiceLength":0,"PlayLength":0,"FileName":"","FileSize":"","MediaId":"","Url":"","AppMsgType":0,"StatusNotifyCode":0,"StatusNotifyUserName":"","RecommendInfo":{"UserName":"","NickName":"","QQNum":0,"Province":"","City":"","Content":"","Signature":"","Alias":"","Scene":0,"VerifyFlag":0,"AttrStatus":0,"Sex":0,"Ticket":"","OpCode":0},"ForwardFlag":0,"AppInfo":{"AppID":"","Type":0},"HasProductId":0,"Ticket":"","ImgHeight":0,"ImgWidth":0,"SubMsgType":0,"NewMsgId":1357981904162237700,"OriContent":"","MMPeerUserName":"@d4d830178e30550380be2175c454951f",
"MMDigest":"","MMIsSend":false,"MMIsChatRoom":false,"MMUnread":true,"LocalID":"1357981904162237688",
"ClientMsgId":"1357981904162237688",
"MMActualContent":"\"杉木\" 撤回了一条消息",
"MMActualSender":"@d4d830178e30550380be2175c454951f","MMDigestTime":"1:02","MMDisplayTime":1503162116,"MMTime":"",
"dev_tag":"这是基于撤消操作消息体"}
```

### Option 2

First `WechatyBro.emit` again `chatFactory._recalledMsgProcess`

Recalled the WebWxApp received the message, rawObj data:

`msg.type()` return `MsgType.RECALLED`
`msg.content()` return `接收到的消息内容`

```json
{"MsgId":"5026368840711665152","FromUserName":"@d4d830178e30550380be2175c454951f","ToUserName":"@ae39ddd7f22214f8f330b68aaa8ec0190702c0c33467b2a23338a77221e6f431",
"MsgType":10002,
"Content":"接收到的消息内容","Status":3,"ImgStatus":1,"CreateTime":1503162474,"VoiceLength":0,"PlayLength":0,"FileName":"","FileSize":"","MediaId":"","Url":"","AppMsgType":0,"StatusNotifyCode":0,"StatusNotifyUserName":"","RecommendInfo":{"UserName":"","NickName":"","QQNum":0,"Province":"","City":"","Content":"","Signature":"","Alias":"","Scene":0,"VerifyFlag":0,"AttrStatus":0,"Sex":0,"Ticket":"","OpCode":0},"ForwardFlag":0,"AppInfo":{"AppID":"","Type":0},"HasProductId":0,"Ticket":"","ImgHeight":0,"ImgWidth":0,"SubMsgType":0,"NewMsgId":5026368840711666000,"OriContent":"","MMPeerUserName":"@d4d830178e30550380be2175c454951f",
"MMDigest":"接收到的消息内容","MMIsSend":false,"MMIsChatRoom":false,"MMUnread":false,"LocalID":"5026368840711665152",
"ClientMsgId":"5026368840711665152",
"MMActualContent":"接收到的消息内容","MMActualSender":"@d4d830178e30550380be2175c454951f","MMDigestTime":"1:07","MMDisplayTime":1503162297,"MMTime":"","_index":33,"_h":56,"_calcing":false,"_offsetTop":1853,"$$hashKey":"0CO",
"dev_tag":"这是基于原先的消息体"}
```

Recalled the WebWxApp did not received the message, rawObj data:

`msg.type()` return `MsgType.RECALLED`
`msg.content()` return `"杉木" 撤回了一条消息`

```json
{"MsgId":"3684395441945462470","FromUserName":"@d4d830178e30550380be2175c454951f","ToUserName":"@ae39ddd7f22214f8f330b68aaa8ec0190702c0c33467b2a23338a77221e6f431",
"MsgType":10002,
"":"\"杉木\" 撤回了一条消息","Status":4,"ImgStatus":1,"CreateTime":1503162479,"VoiceLength":0,"PlayLength":0,"FileName":"","FileSize":"","MediaId":"","Url":"","AppMsgType":0,"StatusNotifyCode":0,"StatusNotifyUserName":"","RecommendInfo":{"UserName":"","NickName":"","QQNum":0,"Province":"","City":"","Content":"","Signature":"","Alias":"","Scene":0,"VerifyFlag":0,"AttrStatus":0,"Sex":0,"Ticket":"","OpCode":0},"ForwardFlag":0,"AppInfo":{"AppID":"","Type":0},"HasProductId":0,"Ticket":"","ImgHeight":0,"ImgWidth":0,"SubMsgType":0,"NewMsgId":8699756819766069000,"OriContent":"","MMPeerUserName":"@d4d830178e30550380be2175c454951f",
"MMDigest":"","MMIsSend":false,"MMIsChatRoom":false,"MMUnread":true,"LocalID":"8699756819766068805",
"ClientMsgId":"8699756819766068805",
"MMActualContent":"\"杉木\" 撤回了一条消息","MMActualSender":"@d4d830178e30550380be2175c454951f","MMDigestTime":"1:07","MMDisplayTime":1503162479,"MMTime":"1:07",
"dev_tag":"这是基于撤消操作消息体"}


I think Recalled type of message, using type () to judge, only through the `msg.id` to obtain the recalled msgId, do not deal with other information, or only as a reference.
Especially when the withdrawn message is not TEXT type.

I recommend choosing `Option 1`

**Comment by binsee** [comment]
I think the code is perfect, no need to change.
Please check the code, please tell me if there is a problem.

**Comment by zixia** [comment]
Yes, the code is very good, that's exactly what's I suggest. :+1: 

And about the two options, I would like to think it by intuition: when a message is revoked, the orignal message should be fired again, with the MsgType set to `RECALLED`.

In detail:
1. When we received a normal message, let's say, an image. The `on('message', cb)` event will be fired, with a `message` of that image as the parameter of `cb`, and the `message` should be `instance of MediaMessage`.
1. After a while, the sender decides to REVOKE that image. Then the `on('message', cb)` event will be fired again, for the revoked message. The `message` should be as same as the last message, except that the MsgType is set to `RECALLED`.

**Comment by binsee** [comment]
@hczhcz
Can I invite you to take the time to review this pr?
Thanks!

**Comment by zixia** [comment]
Thanks all for reviewing the code!
