### PR TITLE
fix(puppet-web): send any type file.

### LINKED ISSUE #710: Cannot send pdf file using MediaMessage
Cannot send pdf file,  It can send pic successfully but not pdf file.
related to #538 
It says pdf file sending 0 data.
get the following sending result:
image

log as follows:

``` shell
TaskList: #TALK #3 #SUCCEED #interval: 3 #taskLog: broadcast file
21:02:29 SILL Message constructor() SN:6
21:02:29 VERB Room say(5步获得AWS的6万云服务代金券.pdf, )
TALK Task Done
21:02:29 VERB PuppetWebBridge getBaseRequest()
21:02:29 VERB PuppetWebBridge proxyWechaty(getBaseRequest, )
21:02:29 SILL PuppetWebBridge execute()
21:02:29 SILL PuppetWebBrowser Browser.execute("return typeof WechatyBro === "undefined"")
21:02:29 SILL StateSwitch Browser:target() is open
21:02:29 SILL StateSwitch Browser:current() is open
21:02:29 SILL PuppetWebBridge execute()
21:02:29 SILL PuppetWebBrowser Browser.execute(" const callback = arguments[arguments.length - 1] const isAsync = (typeof  ... ")
21:02:29 SILL StateSwitch Browser:target() is open
21:02:29 SILL StateSwitch Browser:current() is open
21:02:29 VERB PuppetWebBridge getPassticket()
21:02:29 VERB PuppetWebBridge proxyWechaty(getPassticket, )
21:02:29 SILL PuppetWebBridge execute()
21:02:29 SILL PuppetWebBrowser Browser.execute("return typeof WechatyBro === "undefined"")
21:02:29 SILL StateSwitch Browser:target() is open
21:02:29 SILL StateSwitch Browser:current() is open
21:02:29 SILL PuppetWebBridge execute()
21:02:29 SILL PuppetWebBrowser Browser.execute(" const callback = arguments[arguments.length - 1] const isAsync = (typeof  ... ")
21:02:29 SILL StateSwitch Browser:target() is open
21:02:29 SILL StateSwitch Browser:current() is open
21:02:29 VERB PuppetWebBridge getUploadMediaUrl()
21:02:29 VERB PuppetWebBridge proxyWechaty(getUploadMediaUrl, )
21:02:29 SILL PuppetWebBridge execute()
21:02:29 SILL PuppetWebBrowser Browser.execute("return typeof WechatyBro === "undefined"")
21:02:29 SILL StateSwitch Browser:target() is open
21:02:29 SILL StateSwitch Browser:current() is open
21:02:29 SILL PuppetWebBridge execute()
21:02:29 SILL PuppetWebBrowser Browser.execute(" const callback = arguments[arguments.length - 1] const isAsync = (typeof  ... ")
21:02:29 SILL StateSwitch Browser:target() is open
21:02:29 SILL StateSwitch Browser:current() is open
21:02:29 VERB PuppetWebBrowserCookie read()
21:02:29 SILL PuppetWebBrowserCookie read() webwx_data_ticket,MM_WX_SOUND_STATE,webwx_auth_ticket,MM_WX_NOTIFY_STATE,mm_lang,wxloadtime,wxpluginkey,pgv_si,wxsid,wxuin,webwxuvid,pgv_pvi
21:02:29 VERB PuppetWebBrowser hostname()
21:02:29 SILL PuppetWebBrowser Browser.execute("return document.domain")
21:02:29 SILL StateSwitch Browser:target() is open
21:02:29 SILL StateSwitch Browser:current() is open
21:02:29 SILL PuppetWebBrowser hostname() got qq.com
21:02:29 VERB PuppetWeb self()
21:02:31 SILL PuppetWebEvent onServerDing(heartbeat@browser)
21:02:31 SILL PuppetWebWatchdog onFeed: 60000, HEARTBEAT[heartbeat@browser]
21:02:31 SILL StateSwitch Puppet:target() is live
21:02:31 SILL StateSwitch Puppet:inprocess() is false
21:02:31 SILL PuppetWebWatchdog clearWatchDogTimer() [45] seconds left
21:02:31 SILL PuppetWebWatchdog setWatchDogTimer(60000, HEARTBEAT:[heartbeat@browser])
21:02:31 SILL PuppetWebWatchdog monitorScan(HEARTBEAT)
21:02:31 SILL PuppetWebWatchdog autoSaveSession()
21:02:31 SILL PuppetWebWatchdog memoryCheck() free: 29 MB, require: 4 MB
21:02:31 SILL PuppetWeb send() destination: @@688884a466d382ba5040e2c0bfbe7fa327ac813f4edb6169b2620431f8a385ee, mediaId: @crypt_351c728f_7f1c3d10846338c49d6439fbd8905cd9e6f2b2af3b04e4e4d5ab428c45bdc809ee7c083f0c5581866c6160b38618077469013b833539b6fb6df8342bf10281537534ec64a4e84e630902eb0702007606)
21:02:31 VERB PuppetWebBridge proxyWechaty(sendMedia, @@688884a466d382ba5040e2c0bfbe7fa327ac813f4edb6169b2620431f8a385ee, @crypt_351c728f_7f1c3d10846338c49d6439fbd8905cd9e6f2b2af3b04e4e4d5ab428c45bdc809ee7c083f0c5581866c6160b38618077469013b833539b6fb6df8342bf10281537534ec64a4e84e630902eb0702007606, 49)
21:02:31 SILL PuppetWebBridge execute()
21:02:31 SILL PuppetWebBrowser Browser.execute("return typeof WechatyBro === "undefined"")
21:02:31 SILL StateSwitch Browser:target() is open
21:02:31 SILL StateSwitch Browser:current() is open
21:02:31 SILL PuppetWebBridge execute()
21:02:31 SILL PuppetWebBrowser Browser.execute(" const callback = arguments[arguments.length - 1] const isAsync = (typeof  ... ")
21:02:31 SILL StateSwitch Browser:target() is open
21:02:31 SILL StateSwitch Browser:current() is open
```

### PR DESCRIPTION
**Pull request by binsee**
Fix can't send pdf and more type file.
Now, you can use `m.say(new MediaMessage(file))` send any type file.

Fix #710

### CODE REVIEW

File: src/puppet-web/bridge.ts [hunk 1]
```diff
@@ -397,15 +397,14 @@ export class Bridge {
     }
   }
 
-  public sendMedia(toUserName: string, mediaId: string, type: number): Promise<boolean> {
-    if (!toUserName) {
+  public sendMedia(mediaData: any): Promise<boolean> {
```
Comment (zixia) [inline src/puppet-web/bridge.ts]: Using a type like `any` can make you feel very convenience at start, But it will cause problems in the future because it disables all the benefits from the static type checking.

So please do not use an `any` type here. I have two suggestions:

1. Keep the original style.

Then we will have a function like:

```ts
public sendMedia(
  toUserName: string,
  mediaId: string,
  msgType,
  fileName,
  fileMd5,
  fileSize,
  fileType,
  mmFileExt,
  mmFileId,
)
```

It's very verbose, but it's more clear and prevent us to make mistakes in the future.

2. Or do it the better way: create an interface for this data type.

```
interface MediaData {
  toUserName: string,
  mediaId: string,
  msgType,
  fileName,
  fileMd5,
  fileSize,
  fileType,
  mmFileExt,
  mmFileId,
}

public sendMedia(mediaData: MediaData): Promise<boolean> {
```

I'll prefer the method 2, but you can use either of them, but not the `any` one.

File: src/puppet-web/puppet-web.ts [hunk 2]
```diff
@@ -336,7 +338,7 @@ export class PuppetWeb extends Puppet {
     }
   }
 
-  private async uploadMedia(mediaMessage: MediaMessage, toUserName: string): Promise<string> {
+  private async uploadMedia(mediaMessage: MediaMessage, toUserName: string): Promise<any> {
```
Comment (zixia) [inline src/puppet-web/puppet-web.ts]: The same suggestion as the above review: do not use `any`.

I think here need `interface` too.

File: src/puppet-web/puppet-web.ts [hunk 3]
```diff
@@ -437,7 +450,7 @@ export class PuppetWeb extends Puppet {
     })
     if (!mediaId)
       throw new Error('upload fail')
-    return mediaId as string
+    return { mediaId, mediaData }
```
Comment (zixia) [inline src/puppet-web/puppet-web.ts]: Could you add mediaId into mediaData?

like:

```ts
Object.assign(mediaData, {
  mediaId.
})
```

If we could do this, then here will be more clear, because we can return the interface of `MediaData` here.

File: src/puppet-web/puppet-web.ts [hunk 4]
```diff
@@ -455,17 +468,22 @@ export class PuppetWeb extends Puppet {
       destinationId = to.id
     }
 
-    const mediaId = await this.uploadMedia(message, destinationId)
+    const { mediaId, mediaData } = await this.uploadMedia(message, destinationId)
```
Comment (zixia) [inline src/puppet-web/puppet-web.ts]: Use one return value with an interface here instead of using {}.

Comment (binsee) [inline src/puppet-web/puppet-web.ts]: OK, I'll make changes as you suggest.

File: src/puppet-web/puppet-web.ts [hunk 5]
```diff
@@ -455,17 +468,22 @@ export class PuppetWeb extends Puppet {
...
     const msgType = UtilLib.msgType(message.ext())
 
+    mediaData.FileType = 7
```
Comment (lijiarui) [inline src/puppet-web/puppet-web.ts]: what does `7` means here?  Can it use enum?

Comment (binsee) [inline src/puppet-web/puppet-web.ts]: Reference source: https://res.wx.qq.com/a/wx_fed/webwx/res/static/js/index_4a48aef.js

But the use is unknown, and I'll test it again

```
                                var d,
                                    u = {
                                        FromUserName: c.getUserName(),
                                        ToUserName: e.ToUserName,
                                        FileSize: e.size,
                                        FileMd5: t,
                                        FileName: e.name,
                                        FileType: 7
                                    };
                                if (i) {
                                    var m = angular.extend(u, c.getBaseRequest());
                                    d = angular.extend({}, u),
                                        n({
                                            method: "POST",
                                            url: r.API_checkupload,
                                            data: m
                                        }).success(function(t) {
                                            0 == t.BaseResponse.Ret ? (d = angular.extend(d, {
                                                AESKey: t.AESKey,
                                                Signature: t.Signature
                                            }), e.Signature = t.Signature, a(e, t.MediaId, t)) : (e.MMSendMsg && (e.MMSendMsg.MMFileStatus = r.MM_SEND_FILE_STATUS_FAIL, e.MMSendMsg.MMStatus = r.MSG_SEND_STATUS_FAIL), alert(t.BaseResponse.ErrMsg))
                                        }).error(function(t) {
                                            e.MMSendMsg && (e.MMSendMsg.MMFileStatus = r.MM_SEND_FILE_STATUS_FAIL, e.MMSendMsg.MMStatus = r.MSG_SEND_STATUS_FAIL),
                                                alert("上传失败")
                                        })
```

Comment (binsee) [inline src/puppet-web/puppet-web.ts]: After testing, no valid use of the file type parameter has been found and has been removed.

File: src/puppet-web/puppet-web.ts (hunk 4 above)
Comment (binsee) [inline src/puppet-web/puppet-web.ts]: Code refactoring has been done

**Comment by binsee** [comment]
Known issues:
After the file is sent, the file status on the web page is not updated, but the file has actually been sent successfully.

Sender (bot):
image

Receiver (wechat on pc)
image

**Comment by binsee** [comment]
demo code:

```
  .on('message', async m => {
    try {
      const room = m.room()
      console.log((room ? '[' + room.topic() + ']' : '')
        + '<' + m.from().name() + '>'
        + ':' + m.toStringDigest(),
      )

      if (/^([a-zA-z0-9]{1,5})$/i.test(m.content()) && !m.self()) {

        const file = __dirname + '/test.' + m.content()
        const pathInfo = path.parse(file)
        const fileStat = fs.statSync(file)

        if (fs.existsSync(file) && fileStat.isFile()) {
          await m.say(`请求 ${m.content()} 类型文件`)
          log.info('Bot', `REPLY: File[${pathInfo.base}] size: ${fileStat.size ? fileStat.size : 0}`)
          await m.say(new MediaMessage(file))
        } else {
          await m.say(`请求 ${m.content()} 类型文件失败！没有此类型的文件。`)
        }
      }
    } catch (e) {
      log.error('Bot', 'on(message) exception: %s', e)
    }
  })
```

File: src/puppet-web/puppet-web.ts [hunk 6]
```diff
@@ -384,6 +389,8 @@ export class PuppetWeb extends Puppet {
     const first = cookie.find(c => c.name === 'webwx_data_ticket')
     const webwxDataTicket = first && first.value
     const size = buffer.length
+    const id = 'WU_FILE_' + this.fileId
```
Comment (zixia) [inline src/puppet-web/puppet-web.ts]: Here you save WU_FILE_fileId to id, but in the following code of `formData` you use `this.fileId` instead.

Is this a mistake, or by design?

File: src/puppet-web/puppet-web.ts [hunk 7]
```diff
@@ -399,16 +406,26 @@ export class PuppetWeb extends Puppet {
...
+      FileName: filename,
+      FileSize: size,
+      FileMd5: md5,
+      MMFileId: id,
+      MMFileExt: ext,
+    }
+
     const formData = {
-      id: 'WU_FILE_1',
+      id: this.fileId,
```
Comment (zixia) [inline src/puppet-web/puppet-web.ts]: Here. `fileId` or just `id`? (`const id = 'WU_FILE_' + this.fileId`)?

Comment (binsee) [inline src/puppet-web/puppet-web.ts]: This is a mistake and I will fix it

File: src/puppet-web/puppet-web.ts (hunk 5 above)
Comment (lijiarui) [inline src/puppet-web/puppet-web.ts]: thanks!
